name: 1.0$(Rev:.r)
resources:
  repositories:
    - repository: templates
      type: github
      name: gavanlamb/azure-devops-templates
      endpoint: Expensely
    - repository: expensely-templates
      type: github
      name: expensely/azure-devops-templates
      endpoint: Expensely

trigger:
  batch: true
  branches:
    include:
      - "main"

pr: none

stages:
  - stage: production
    displayName: Production
    variables:
      - template: variables/production.ap-southeast-2.yml@expensely-templates
    pool:
      vmImage: windows-latest
    jobs:
      - template: templates/environment.release.yml
        parameters:
          environment: ${{ variables.environment }}
          terraformServiceConnectionName: ${{ variables.terraformServiceConnectionName }}
          awsServiceConnectionName: ${{ variables.awsServiceConnectionName }}
          stateBucketName: ${{ variables.terraformStateBucketName }}
          stateLockTableName: ${{ variables.terraformStateLockTableName }}
          region: ${{ variables.region }}
          planAdditionalCommandOptions: '-var-file=variables/production.$(region).tfvars'
          bucketName: expensely.app
